spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  header: Authorization
  secret: a72qsnWndnuvEA29RYVpWQMvopwtPu8yi149KLw4iA07bXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400