spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mariadb

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true